services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./client
        target: /home/node
      - type: volume
        target: /home/node/node_modules
    ports:
      - "5173:5173"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      MONGO_URL_FILE: /run/secrets/mongo-url
    secrets:
      - mongo-url
    volumes:
      - type: bind
        source: ./api/src
        target: /app/src
    ports:
      - "3001:80"

  db:
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: dymaroot
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo-admin-passe
    secrets:
      - mongo-admin-passe
    volumes:
      - type: volume
        source: dbtest
        target: /data/db

volumes:
  dbtest:

secrets:
  mongo-url:
    file: ./secrets/mongo-url
  mongo-admin-passe:
    file: ./secrets/mongo-admin-passe
